<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>PasteBeside</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>cmgoodquist.pastebeside</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>PasteBeside</ApplicationPublisher>
    <!-- Package Description -->
    <Description>PasteBeside powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      CSharpMarkup;
      Material;
      Toolkit;
      MVUX;
      ThemeService;
      SkiaRenderer;
	  Hosting;
	  Navigation;
	  Configuration;
    </UnoFeatures>
    <UserSecretsId>157b1c3a-bf0e-44ea-9353-848a86edc5ec</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BoundaryModels\BoundaryModels.csproj" />
  </ItemGroup>

</Project>
